version: "3.2"
services:
  php:
    build: 
      context: .
    ports:
      - "30001:80"
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=luna
      - MYSQL_PASSWORD=secret 
      - MYSQL_DATABASE=lunaproject
